### ISSUE TITLE
Add support to C#, dotnet & JSON

### ISSUE THREAD

**Issue by eliumoraes** [GreenAsh/code-highlighter#24]
I love the work you did with the plugin.
Would like to find C#/dotnet and also JSON in the options.

**Comment by GreenAsh** [comment]
Hi @eliumoraes,
will try to add C# and JSON this weekend.

**Comment by GreenAsh** [comment]
done

**Comment by GreenAsh** [comment]
@eliumoraes BTW you can check a code block released by miro.com, that can replace this plugin, see [Write code in Miro and ship better-quality software](https://community.miro.com/product-news-31/write-code-in-miro-and-ship-better-quality-software-10544)
