### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by d83b38** [GreenAsh/code-highlighter#4]
The plugin doesn't seem to work. I log into the installation page, then I am transferred to the main page of Miro. There is nothing on the boards.

**Comment by juliandcf** [comment]
I also tried to install the plugin but could not do it.

**Comment by GreenAsh** [comment]
Installation works. Smth wrong with the plugin initialization inside miro.com on board loading stage.

**Comment by GreenAsh** [comment]
Fixed installation link.
@juliandcf @d83b38 could you check it pls?
