### ISSUE TITLE
Add gherkin support

### ISSUE THREAD

**Issue by kjgarza** [GreenAsh/code-highlighter#9]
I use gherkin syntax to write user stories and acceptance criteria. It would amazing to have that highlighted in Miro and prismjs does support it so I guess is simple. https://medium.com/@nic/writing-user-stories-with-gherkin-dda63461b1d2

**Comment by GreenAsh** [comment]
@kjgarza I'm going to release a new version with Gherkin support on February 6, 2022.
To show the "Gherkin" button in the widget menu you will need to configure it in the plugin settings.

**Comment by kjgarza** [comment]
i am struggling to find the plugin settings now that the smart meeting features came out. can you point me in which direction should i go? thanks @GreenAsh

**Comment by GreenAsh** [comment]
I would suggest checking that the plugin loaded correctly. 
Please check if you could see the plugin buttons in the widget menu:
![menu-buttons](https://i.ibb.co/KKpBRPn/Screenshot-2022-02-09-at-2-02-42-am.png)

The settings button should be on the bottom left panel, check if the panel isn't collapsed:
![collapsed-panel](https://i.ibb.co/F80DT7P/Screenshot-2022-02-09-at-2-09-27-am.png)
![settings-button](https://i.ibb.co/2c24L0N/Screenshot-2022-02-09-at-2-09-49-am.png)

Alternatively, you can change the plugin settings on the settings page by opening it directly in your browser: https://miro-code-highlighter.glitch.me/settings.html. After changing values on the page switch to a page/tab with Miro board in your browser and reopen widget menu, e.g. by reselecting widget/widgets on the board.

If the plugin loaded correctly and you still can't find the settings button, it would be great if you could share an image of the miro UI you see, including all panels: left sidebar, bottom left panel, bottom right panel, etc.

@kjgarza

**Comment by kjgarza** [comment]
Found it, i think the new UI changed the  position of the settings 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/1092861/153325078-ccbbfd4f-cb05-4e8e-9bcc-b9258b2e7567.png">

But I manage to have it working thank you so much.

Additional comment: it seems to be that there is a character limit for the gherkin conversion (6000 chr). The plugin seems to be sending an error when converting a long text. just FYI.

Thank for this; its truly useful

**Comment by GreenAsh** [comment]
A huge thank you 🤘 

> it seems to be that there is a character limit for the gherkin conversion (6000 chr). The plugin seems to be sending an error when converting a long text. just FYI.

Yeah, thx, this is known behavior. Widgets in Miro have their own size limit and it is around 6000 characters. Therefore, after formatting the text, the plugin checks whether it will fit within this limit or not, and if not, it shows an error message.
